# Generated by Django 3.2.9 on 2022-01-04 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('animal', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('animal', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('other', 'Other')], max_length=50)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female'), (9, 'Not Applicable')], default=0)),
                ('eye_color', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('brown', 'Brown'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('gray', 'Gray')], default='', max_length=50)),
                ('color', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('brown', 'Brown'), ('orange', 'Orange'), ('red', 'Red'), ('pink', 'Pink'), ('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('gray', 'Gray')], default='', max_length=50)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('microchip', models.CharField(blank=True, default='', max_length=15)),
                ('information', models.CharField(blank=True, default='', max_length=5000)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('reunited', 'Reunited')], max_length=50)),
                ('breed', models.ManyToManyField(blank=True, to='api.Breed')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pet')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
