# Generated by Django 3.2.9 on 2021-11-27 03:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='pet',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.pet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
