# Generated by Django 3.2.9 on 2022-01-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_photo_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
