# Generated by Django 4.0.6 on 2022-07-22 21:12

import json
import os
from django.db import migrations


def insert_pet_breeds(apps, schema_editor):
    Breed = apps.get_model("api", "Breed")
    breed_list = []
    with open(os.path.join(os.path.dirname(__file__), "data/breeds.json"), "r") as f:
        data = json.load(f)
    for breed in data["dog_breeds"]:
        breed_list.append(Breed(name=breed, animal="dog"))
    for breed in data["cat_breeds"]:
        breed_list.append(Breed(name=breed, animal="cat"))
    Breed.objects.bulk_create(breed_list)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20220707_2132"),
    ]

    operations = [migrations.RunPython(insert_pet_breeds)]
