# Generated by Django 3.2.9 on 2021-11-27 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211127_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='post',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
            preserve_default=False,
        ),
    ]
