# Generated by Django 4.0.6 on 2022-08-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220722_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breed',
            old_name='animal',
            new_name='species',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='type',
            new_name='species',
        ),
    ]
