# Generated by Django 3.2.9 on 2022-01-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_photo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
