# Generated by Django 3.2.9 on 2022-04-08 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220317_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('location_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('resolved', 'Resolved')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='animal',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='information',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='pet',
        ),
        migrations.AlterField(
            model_name='photo',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='PetLastKnownLocation',
        ),
        migrations.AddField(
            model_name='post',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.pet'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.post'),
            preserve_default=False,
        ),
    ]
