# Generated by Django 3.2.9 on 2021-11-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211127_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='description',
            new_name='information',
        ),
    ]
