# Generated by Django 3.2.9 on 2022-01-19 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_photo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
    ]
