# Generated by Django 3.2.9 on 2022-01-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
