# Generated by Django 3.2.9 on 2021-12-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211215_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='microchip',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
    ]
