# Generated by Django 4.1 on 2022-08-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20220803_0020"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("hex", models.CharField(max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name="pet",
            name="coat_color",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="eye_color",
        ),
        migrations.AddField(
            model_name="pet",
            name="coat_colors",
            field=models.ManyToManyField(
                related_name="pet_coat_colors", to="api.color"
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="eye_colors",
            field=models.ManyToManyField(related_name="pet_eye_colors", to="api.color"),
        ),
    ]
