# Generated by Django 4.1 on 2022-08-06 21:00

import json
import os
from django.db import migrations


def insert_colors(apps, schema_editor):
    Color = apps.get_model("api", "Color")
    with open(os.path.join(os.path.dirname(__file__), "data/colors.json"), "r") as f:
        data = json.load(f)
        colors = list(
            map(lambda color: Color(name=color["name"], hex=color["hex"]), data)
        )
        Color.objects.bulk_create(colors)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_color_remove_pet_coat_color_remove_pet_eye_color_and_more"),
    ]

    operations = [migrations.RunPython(insert_colors)]
