# Generated by Django 3.2.9 on 2022-01-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pet_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.ManyToManyField(blank=True, to='api.Breed'),
        ),
    ]
