# Generated by Django 3.2.9 on 2022-02-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220202_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
        migrations.AddField(
            model_name='pet',
            name='user_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='api.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='api.UserProfile'),
        ),
    ]
