# Generated by Django 3.2.9 on 2021-12-31 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_comment_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
