# Generated by Django 3.2.9 on 2022-02-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220202_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='location_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='location_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
