# Generated by Django 3.2.9 on 2022-02-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220203_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='user_profile',
            new_name='user',
        ),
    ]
