# Generated by Django 3.2.9 on 2022-02-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_user_profile_useraddress_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='location_latitude',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='location_longitude',
        ),
        migrations.CreateModel(
            name='PetLastKnownLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.pet')),
            ],
        ),
    ]
