# Generated by Django 3.2.9 on 2022-02-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220203_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petlastknownlocation',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_known_location', to='api.pet'),
        ),
    ]
